### ISSUE TITLE
Shouldn't the hazard frequency be 0.01 for all events in the demo?

### ISSUE THREAD

**Issue by qlejeune** [davidnbresch/climada#4]
Event 99 has a frequency of 0.001 at the moment, unlike all others.

**Comment by ThomasRoosli** [comment]
Hi qlejeune
I will try to help you. At the moment I cannot replicate your findings. Are you following the script "climada_demo_step_by_step.m"? If yes try to pull a current version of climada from GitHub. If no please specify in which script or function the hazard was created. 
Best,
ThomasRoosli

**Comment by qlejeune** [comment]
Hi @ThomasRoosli 
I've just cloned the repository.
The file I'm referring to is called Excel_hazard, and is located under climada-master/data/hazards
Best,
qlejeune

**Comment by davidnbresch** [comment]
Dear all,

this file (Excel_hazard.xlsx, https://github.com/davidnbresch/climada/blob/master/data/hazards/Excel_hazard.xlsx <https://github.com/davidnbresch/climada/blob/master/data/hazards/Excel_hazard.xlsx>) ist just a DEMO file, to show that one could also import a hazard set from an Excel file and could use non-uniform frequencies. 
Excel hazard is not used in the step-by-step guide at all.

With best regards,
David


Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch <mailto:dbresch@ethz.ch>, dbresch@meteoswiss.ch <mailto:dbresch@meteoswiss.ch>
skype: davidnbresch
www.usys.ethz.ch/en/people/profile.html?persid=49820 <http://www.usys.ethz.ch/en/people/profile.html?persid=49820>, http://www.wcr.ethz.ch <http://www.wcr.ethz.ch/>

**Comment by qlejeune** [comment]
Dear @davidnbresch  and @ThomasRoosli,

Thanks for your help and your clarifications.

Best,
qlejeune

**Comment by ThomasRoosli** [comment]
Dear @qlejeune  
I am glad we could clarify the issue. Thanks for using climada and interacting with us.
Best,
ThomasRoosli
