### ISSUE TITLE
climada_EDS_calc mentions climada_EDS_calc_parfor but the latter does not exist

### ISSUE THREAD

**Issue by bguillod** [davidnbresch/climada#7]
At line 23 in climada_EDS_calc.m it says:
%   See also climada_EDS_calc_parfor for a parallelized version (beta)
However, climada_EDS_calc_parfor does not appear to exist (at least I did not find it). Should that line be removed then?

**Comment by davidnbresch** [comment]
Dera Benoît,

good point, there existed once such a version, but it did not perform. Yes, please remove the line - and thanks for spotting this!

Mit herzlichem Gruss,
David


Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch <mailto:dbresch@ethz.ch>, dbresch@meteoswiss.ch <mailto:dbresch@meteoswiss.ch>
office: +41 44 632 77 87
mobile: +41 79 770 15 92
skype: davidnbresch
https://www.usys.ethz.ch/en/people/profile.david-bresch.html
http://www.wcr.ethz.ch <http://www.wcr.ethz.ch/>

**Comment by bguillod** [comment]
Great thanks, I'll replace it by a mention to my new fast version once I've that one ready to be committed.
